version: "3.7"

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
          - "81:80" # В nginx порт должен совпадать с открытым портом из-за особенностей механизма редиректов фласка
        volumes:
          - ./backend/app/static:/static
        depends_on:
          - app

    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - PORT=8080
        env_file:
          - ./backend/.env
        environment:
          - APP_ENV=prod
          - APP_DEBUG=0
        ports:
          - "8080:8080"
networks:
  nginx_network:
    driver: bridge