version: "3.7"

services:
    nginx:
        build: nginx
        volumes:
          - ./frontend/admin/build:/static
        ports:
          - "81:80"
        depends_on:
          - api

    api:
        build: backend
        env_file:
          - ./backend/.env
        environment:
          - PORT=8080
        ports:
          - "8080:8080"
networks:
  nginx_network:
    driver: bridge