name: 'Python lint'

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-mypy: false
          use-isort: false
          python-root-list: "backend/app"
          extra-pycodestyle-options: "--max-line-length=120"
          extra-flake8-options: "--ignore=F401,E501,W"